rd /s /q R:\Temp
rd /s /q R:\Firefox
rd /s /q R:\Chrome
rd /s /q R:\Chrome_hobby
rd /s /q R:\IE
rd /s /q R:\Downloads
rd /s /q R:\nFinder
rd /s /q R:\Jane
rd /s /q R:\Notepad++
rd /s /q R:\V2
rd /s /q R:\Java
rd /s /q R:\DownThemAll
rd /s /q R:\7zip
rd /s /q R:\CravingExplorer
rd /s /q R:\WinMerge
rd /s /q R:\Word
rd /s /q R:\Excel
rd /s /q R:\PowerPoint
