mkdir R:\Temp
mkdir R:\Firefox
mkdir R:\Chrome
mkdir R:\Chrome_hobby
mkdir R:\IE
mkdir R:\Downloads
mkdir R:\nFinder
mkdir R:\Jane
mkdir R:\Notepad++
mkdir R:\V2
mkdir R:\Java
mkdir R:\DownThemAll
mkdir R:\7zip
mkdir R:\CravingExplorer
mkdir R:\WinMerge
mkdir R:\Word
mkdir R:\Excel
mkdir R:\PowerPoint
